version: '3'
services:
  atlassian-jira:
    image: cptactionhank/atlassian-jira
    ports:
      - "9271:8080"
    volumes:
      - ./jira:/var/atlassian/jira
      - ./logs:/opt/atlassian/jira/logs
    restart:
      always
